#define mts_AlugarMotoFaggio 1
#define mts_MochilaMelhor 2

#define mts_CompreCelular 3
#define mts_Selfie 4

#define mts_Capacete 5

#define mts_EmpregoMotoboyEntregas 6

#define mts_ComprarSkin 7

#define mts_AprendaSafeZone 8
#define mts_AprendaPresentes 9

#define mts_Malhar 10
#define mts_Durateston 11

#define mts_MateSuaFome 12 // fome dps da malhar pra recuperar a vida da malhada
#define mts_BebidaAlcoolica 13 // colete 1
#define mts_CurarPigPeen 14 // colete 2

#define mts_LicencaDeArmaCIVILIAN 15
#define mts_AntiDM_Intro 16
#define mts_AntiDM_SeRender 17
#define mts_ComprarArmaAmmunation 18
#define mts_ComprarMunicaoAmunation 19
#define mts_AntiDM_SacarArma 20
#define mts_AntiDM_MirarArma 21
#define mts_Atirar 22
#define mts_AssaltarNPCLoja 23
#define mts_LavarDinheiroSujo 24

#define mts_PlantarMaconha 25 // colete 3 (essa aqui pra plantar mais rapido primeira vez 1 min)
#define mts_UsarMaconha 26
#define mts_PvpColherErva 27

#define mts_HotelMaconha 28
#define mts_HotelDinheiro 29

#define mts_SaldoDinheiroBancoATM 30
#define mts_DepositarDinheiroBanco 31
#define mts_SacarDinheiroBancoATM 32
#define mts_RoubarATM 33
#define mts_RoubarCasa 34

// saiu de rook
#define mts_LeaveTutorialIsland 35


#define mts_TirarLicencaTerrestreA 36
#define mts_AlugueUmaWayfarer 37

#define mts_MateSuaSede 38

#define mts_Morphine 39
#define mts_Bandage 40
#define mts_Medkit 41

// roubar partner primeira das em dupla pq é mais divertida
#define mts_RoubarPartner 42
#define mts_SerCumpliceDeUmRoubo 43
#define mts_BloodBag 44


#define mts_FicarProcuradoPelaPolicia 45
#define mts_CrimeFugirAbordagem 46
#define mts_PvpReagirRendicao 47
#define mts_PvpAtirarInocente 48
#define mts_DiminuirLimparNivelDeProcuradoTattoBarberShops 49
#define mts_SerPreso 50
#define mts_CrimeProcuradoRoubo 51
#define mts_CrimeProcuradoAgressao 52
#define mts_CrimeTentativaHomicidio 53
#define mts_MetaColete1 54 // meta colete = 1,2,3

#define mts_AnimPickup 55
#define mts_MenuAnim 56
#define mts_ConfigAnim 57

#define mts_TirarLicencaTerrestreB 58
#define mts_AlugarCarroManana 59
#define mts_CintoDeSeguranca 60
#define mts_TranqueSeuVeiculo 61

#define mts_CrimeRoubarCarro 62
#define mts_Mascara 63
#define mts_PvpColocarMascara 64
#define mts_CrimeFalsidadeIdeologica 65

#define mts_AgendaCelular 66
#define mts_MsgCelular 67
#define mts_LigarParaCelular 68

#define mts_AssaltarPlayerOFF 69

#define mts_EmpregoPilotoAviao 70

#define mts_EmpregoMedico 71
#define mts_ReviverUTI 72
#define mts_MandarAlbergueMedico 73
#define mts_ReviverMedico 74
#define mts_CurarAmbulancia 75

#define mts_SairOrgPrefeitura 76

#define mts_PlantarFolhaDeCocaina 77
#define mts_FabricarCocaina 78
#define mts_UsarCocaina 79
#define mts_FabricarCrack 80
#define mts_UsarCrack 81
#define mts_MetaColete2 82

#define mts_CompreMateriais 83
#define mts_FabriquePistola 84
#define mts_EmpregoVendedorDeArmasSellgun 85

#define mts_VipAccountInfo 86

#define mts_4LocalGritoSussurro 87
#define mts_Jornal 88

#define mts_ConsertarVeiculoOficina 89
#define mts_ComprarAirbagOficina 90
#define mts_AbastecerVeiculoGasStation 91
#define mts_AbastecerVeiculoGalaoDeGasolina 92
#define mts_Eject 93

#define mts_MecanicoGuincho 94
#define mts_MecanicoConsertarVeiculoDeAlguem 95

#define mts_TirarLicencaTerrestreC 96
#define mts_RotasEmpregoMotoristaDeOnibus 97
#define mts_TirarLicencaTerrestreD 98
#define mts_AprendaSuprimentos 99

#define mts_ComprarVeiculo 100
#define mts_EstacionarVeiculo 101
#define mts_ComprarLVLSeguroVeiculo 102
#define mts_ComprarLVLAlarmeVeiculo 103
#define mts_ComprarLVLTrancaVeiculo 104
#define mts_VipVehicleInfo 105
#define mts_MyVehicleLocate 106

#define mts_TirarLicencaTerrestreE 107
#define mts_EmpregoCaminhoneiroCaminhao 108

#define mts_ComprarBlesses 109

#define mts_BilheteLoterica 110

#define mts_PvpRoubarCarro 111 // 100 pts pra poder roubar veiculo (por causa da restricao de lvl)
#define mts_SejaAbordado 112

#define mts_FightStyle 113
#define mts_Stanozolol 114

#define mts_EmpregoPescadorPescar 115
#define mts_EmpregoMineradorMinerar 116

#define mts_LicencaDeArmaLSPD 117
#define mts_EntrarCOPLSPD 118
#define mts_6RadioORG 119
#define mts_EquipCop 120
#define mts_EquipCop2 121
#define mts_ColeteCopMed 122
#define mts_EntregarUmaTransportBag 123
#define mts_MandarAlberguePM 124
#define mts_AtenderChamadoHQgpsbizz 125
#define mts_AtenderChamadoHQgpsatm 126
#define mts_AtenderChamadoHQgpshouse 127
#define mts_AtenderChamadoHQlveh 128
#define mts_AtenderChamadoHQpartner 129
#define mts_AbordagemPolicial 130
#define mts_PrenderProcuradoLevarAtePrisao 131
#define mts_MeleeTaze 132
#define mts_PistolTaze 133
#define mts_QuebrarCarro 134
#define mts_FastArrestHP 135
#define mts_FastArrestOFF 136
#define mts_CloseOperationGZeBIZZ 137
#define mts_SeizureOperationHouseAndFactionHQ 138
#define mts_DevolverMovelRoubado 139
#define mts_GanharPackage 140
#define mts_PvpPackage 141
#define mts_LocateEmpregoDetetive 142
#define mts_EntrarFBI 143
#define mts_EncontrarAssassinosCadaveres 144
#define mts_TaskSystemCOP 145
#define mts_CorrupcaoCOP 146

#define mts_AssaltarPlayerON 147
#define mts_LadraoDeVeiculosDesmanchar 148
#define mts_EntrarEmUmaFaccao 149
#define mts_ComprarRadio 150
#define mts_6RadioFaction 151
#define mts_ChecarSalarioFaction 152
#define mts_ChecarFactionTax 153
#define mts_EquiparArmamentosFaction 154
#define mts_EquiparDrogasFaction 155
#define mts_ArmaDeMentiraSinalizador 156

#define mts_RoubarGroup 157
#define mts_PvpGroupRob 158
#define mts_CapturarGangZone 159
#define mts_VehicleFaction 160
#define mts_VipFactionVip 161
#define mts_RoubarArmazem 162


#define mts_TirarLicencaMaritima 163
#define mts_EmpregoPirataCacaTesouro 164 
#define mts_EmpregoPirataTitanic 165
#define mts_ComprarCasa 166
#define mts_GuardarDinheiroCasa 167
#define mts_TrocarSenhaCasa 168
#define mts_FecharPortaCasa 169
#define mts_ComprarTrancaCasa 170
#define mts_ConvideUmAmigoReffer 171
#define mts_VipHouseInfo 172
#define mts_GuardarDrogasOuMaterialCasa 173
#define mts_SoltarPresoEmpregoAdvogado 174
#define mts_EstuprarDildo 175
#define mts_DSTPills 176
#define mts_RoupaAntiEstupro 177
#define mts_ArmaBrancaTacoDeBaseball 178
#define mts_AprendaDeposito 179
#define mts_FugirPrisao 180
#define mts_Sequestrar 181
#define mts_ChecarTrancaFac 182
#define mts_LucroFac 183
#define mts_QueimarCofre 184
#define mts_CharacterKill 185
#define mts_TaskSystemCriminal 186
#define mts_RoubarDP 187
#define mts_FlashBang 188
#define mts_SmokeGrenade 189

#define mts_TaskSystemCivilian 190
#define mts_TripleBetCassino 191
#define mts_TirarLicencaTerrestreF 192
#define mts_RotasEmpregoMaquinista 193
#define mts_CompreSuaEmpresa 194
#define mts_ControleProdutosEmpresa 195
#define mts_ControleProtectivePointsEmpresa 196
#define mts_VipBizzInfo 197


// daqui pra baixo e novidade
// 2.0
// 3.0
// 4.0

#define mts_CrimeResistPrisionScrollWeapon 198
#define mts_RobTransportBag 199
#define mts_BuyPillsPharmacyCheaper 200
#define mts_BuyMorphinePharmacyCheaper 201
#define mts_BuyBandagePharmacyCheaper 202
#define mts_ChangeOutfitHotel 203
#define mts_ChangeOutfitHouse 204
#define mts_ReadJobTutorialWithN 205
#define mts_PickFavelaBaileBetterPresent 206
#define mts_PutLaserWeapon 207
#define mts_PaintFactionGraffiti 208
#define mts_AtenderChamadoHQgraffiti 209

// adicionar observação para desativar lock ON, pq n funciona o roubo com lockon:
// mts_AssaltarNPCLoja
// mts_AssaltarPlayerON
// mts_AssaltarPlayerOFF
// mts_FastArrestOFF

// // editar texto pra avisar que o preço da durateston muda de acordo com o nivel de musculo
// mts_Durateston


// // avisar que tem que sair do veiculo e apertar Y pra executar a ação
// mts_AbastecerVeiculoGasStation
// #define mts_ConsertarVeiculoOficina 89
// #define mts_ComprarAirbagOficina 90

#define mts_VencerArenaDM 210
#define mts_VencerArenaTDM 211
#define mts_VencerArmsRace 212
#define mts_VencerCTF 213
#define mts_VencerMutants 214
#define mts_VencerNoRespawnDM 215

#define mts_KillArenaDMEventKill 216

#define mts_FullPvpDefendRobInYourHouse 217
#define mts_FullPvpDefendRobInYourVehicle 218

#define mts_AutoTargetSurrenderSystem 219

#define mts_GetMaxHpGYM150 220

#define mts_FbiGpsCorpse 221

#define mts_ExtraRobCriminalLvlBizz 222
#define mts_ExtraRobCriminalLvlATM 223
#define mts_ExtraRobCriminalLvlHouse 224
#define mts_ExtraRobCriminalLvlHQ 225

#define mts_ExtraMoneyRobRichHouse 226 // cada 1kk abre um bonus grande ao roubar
#define mts_ExtraMoneyRobRichFacHQ 227 // cada 1kk abre um bonus grande ao roubar

#define mts_DangerousDrivingLoseDriverLicense 228
#define mts_IlegalWeaponLoseWeaponLicense 229

#define mts_PutHitmanContract 230
#define mts_GetHitmanContract 231
#define mts_DieHitmanContract 232
#define mts_KillHitmanContract 233

#define mts_HandshakePlayerNametagSameCountry 234
#define mts_HandshakePlayerNametagVoiceOn 235
#define mts_HandshakePlayerNametagVoiceOff 236
#define mts_HandshakePlayerNametagVoiceNoMic 237

#define mts_BringCriminalToPrisionGiveMoreSkill 238

#define mts_HouseHQFactionLock 239

#define mts_CheckAndUnderstandFactionTax 240

#define mts_PvpMakeWeapon 241
#define mts_PvpStartGraffiti 242
#define mts_PvpDriveByH 243
#define mts_PvpCopJailCriminal 244
#define mts_PvpCopTazeCriminal 245
#define mts_PvpCopCriminalReciveWantedLvl 246
#define mts_PvpCopUseMegaphone 247
#define mts_PvpCopOperation 248
#define mts_PvpFactionBreakHouseDoor 249
#define mts_PvpFactionBurnFactionHQ 250
#define mts_PvpCarjackVehNoKeys 251

#define mts_CrimeShotInPublic 252

#define mts_CrimeKidnapping 253
#define mts_CrimeMurder 254
#define mts_CrimeDangerousDriving 255
#define mts_CrimeTrafficking 256
#define mts_CrimeIllegalPortingOfWeapons 257
#define mts_CrimeIllegalPortingOfDrugs 258
#define mts_CrimeAccomplice 259
#define mts_CrimeNoDriversLicense 260
#define mts_CrimeHomeInvasion 261
#define mts_CrimeTerritoryWar 262
#define mts_CrimeRape 263
#define mts_CrimeStealingArmyPackage 264
#define mts_CrimeTerrorism 265
#define mts_CrimeCorruption 266
#define mts_CrimeDisrespectThePoliceOrder 267
#define mts_CrimeMurderWithExcessiveBrutality 268
#define mts_CrimeGangGraffiti 269
#define mts_CrimeSerialKiller 270

#define mts_RunIlegalRace 271
#define mts_WinIlegalRace 272
#define mts_RunFullIlegalRace 273
#define mts_WinFullIlegalRace 274

#define mts_PassangerShamal 275

#define mts_StatsSkills 276
#define mts_UrinateHotel 277
#define mts_UrinateHouse 278
#define mts_UrinateHQ 279
#define mts_ShitYourself 280
#define mts_SleepHotel 281
#define mts_SleepHouse 282
#define mts_SleepHQ 283
#define mts_FaintFromSleep 284
#define mts_MsgCelularOFF 285

#define mts_GZRewardMary 286
#define mts_GZRewardCoca 287
#define mts_GZRewardKlark 288

#define mts_IdiomEnglish 289
#define mts_IdiomAny 290

#define mts_ConfigDisableAllTXD 291
#define mts_ConfigEnableAllTXD 292

#define mts_ConfigDisableShotDirectionTXD 293
#define mts_ConfigEnableShotDirectionTXD 294

#define mts_ConfigEnableRedBloodEffectTXD 295
#define mts_ConfigDisableRedBloodEffectTXD 296

#define mts_ConfigDisableTicketsAlertTXD 297
#define mts_ConfigEnableTicketsAlertTXD 298

#define mts_GzExtendShowRadar 299
#define mts_TryRobBlockedHQFacOwnGZ 300
#define mts_TryBurnBlockedHQFacOwnGZ 301
#define mts_EnterHQFromBoca 302
#define mts_EnterGzOwnedFullPvp 303
#define mts_StealHouseOwnedGZ 304
#define mts_InjustKill 305
#define mts_DrinkCoffe 306
#define mts_EatBanana 307

#define mts_DieAloneDontLoseInv 308

#define mts_JoinArenaHotelMap 309
#define mts_JoinArenaPaintballMap 310

#define mts_GetFastArrestPoliceBoat 311

#define mts_RemountDismantlingLostUnusedCar 312

#define mts_AddTmpFacMember 313
#define mts_JoinTmpFacMember 314
#define mts_CombatHelmet 315
#define mts_CombatArmor 316
#define mts_CombatLegs 317
#define mts_CombatShoulders 318
#define mts_UseInvItem 319
#define mts_DropInvItem 320
#define mts_MoveInvItem 321
#define mts_RobTargetInvItem 322
#define mts_PutInvItemOnHouse 323
#define mts_CheckILXJornalAds 324
#define mts_SendMyLocation 325
#define mts_FindFriendLocation 326
#define mts_PutCorpseIntoTrunk 327
#define mts_ThrowCorpseIntoTheWater 328
#define mts_SetFastArrestPoliceBoat 329

#define mts_CallMechanicService 330
#define mts_CallPoliceService 331
#define mts_CallMedicService 332

#define mts_FactionWar 333

#define mts_ColabInfo 334
#define mts_RefferInfo 335

#define mts_HelpNoobPartner 336
#define mts_HelpNoobBloodbag 337

#define mts_UseAdrenalineRevive 338

// mts_LigarParaCelular
// falar sobre o voip


// editar pra falar pra chamar pessoas na rua ou no jornal
// avisando que essas pessoas ganham recompensa ao te novato a passar de missao pelo servidor
// e eles vao querer ajudar
// mts_BloodBag
// mts_RoubarPartner

#define mts_AddNewMission 339